baseURL = 'https://willson-wen.github.io/'
languageCode = 'en-us'
title = '卡萨丁'
theme = 'PaperModX'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  author = "卡萨丁"
  description = "AI训练师|AICoding爱好者｜户外，球类，健身爱好者"
  
  [params.profileMode]
    enabled = true
    title = "卡萨丁"
    subtitle = "AI训练师|AICoding爱好者｜户外，球类，健身爱好者"
    imageUrl = "images/new-avatar.jpg"
    imageTitle = "handsome boy"
    imageWidth = 320
    imageHeight = 294
    

  
  [[params.socialIcons]]
    name = "Github-Simple"
    url = "https://github.com/willson-wen?tab=repositories"
  

  [[params.socialIcons]]
name = "xiaohongshu-custom"
url = "https://www.xiaohongshu.com/user/profile/6017e4d7000000000100bf35"

  [[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/sanzhui1?igsh=MXZoZXV1bGI5eGo1NQ%3D%3D&utm_source=qr"

  [[params.socialIcons]]
name = "douyin-custom"
url = "https://v.douyin.com/iUw1F2bh-L8/"

[params.fuseOpts]
isCaseSensitive = false
includeMatches = true
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  
  [[menu.main]]
    name = "Post"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 40
